
CREATE TABLE AGE_PREFER
(
  AGE_PREF    VARCHAR(50) NOT NULL COMMENT '파트너 연령',
  AGE_PREF_ID VARCHAR(50) NOT NULL COMMENT '파트너 연령ID',
  PRIMARY KEY (AGE_PREF_ID)
) COMMENT '파트너 연령 선호';

CREATE TABLE CAR_LICENCE_PREFER
(
  CAR_LIC_PREF    VARCHAR(50) NOT NULL COMMENT '차량/면허 여부',
  CAR_LIC_PREF_ID VARCHAR(50) NOT NULL COMMENT '차량/면허 여부 ID',
  PRIMARY KEY (CAR_LIC_PREF_ID)
) COMMENT '차량/면허 여부 필요';

CREATE TABLE CERTIFICATION_PREFER
(
  CERT_PREF    VARCHAR(50) NOT NULL COMMENT '자격증 소유 여부',
  CERT_PREF_ID VARCHAR(50) NOT NULL COMMENT '자격증 소유 여부 ID',
  PRIMARY KEY (CERT_PREF_ID)
) COMMENT '자격증 소유 선호';

CREATE TABLE GENDER
(
  GENDER    VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_ID VARCHAR(50) NOT NULL COMMENT '성별ID',
  PRIMARY KEY (GENDER_ID)
) COMMENT '성별';

CREATE TABLE GENDER_PREFER
(
  GENDER_PREF    VARCHAR(50) NOT NULL COMMENT '파트너성별',
  GENDER_PREF_ID VARCHAR(50) NOT NULL COMMENT '파트너성별ID',
  PRIMARY KEY (GENDER_PREF_ID)
) COMMENT '파트너 성별 선호';

CREATE TABLE JOBTYPE_PREFER
(
  JOBTYPE_PREF    VARCHAR(50) NOT NULL COMMENT '고용형태',
  JOBTYPE_PREF_ID VARCHAR(50) NOT NULL COMMENT '고용형태_ID',
  PRIMARY KEY (JOBTYPE_PREF_ID)
) COMMENT '고용형태 선호';

CREATE TABLE LEVEL
(
  LEVEL    VARCHAR(50) NULL     COMMENT '치매진행단계',
  LEVEL_ID VARCHAR(50) NOT NULL COMMENT '치매진행단계ID',
  PRIMARY KEY (LEVEL_ID)
);

CREATE TABLE MATCHING_A
(
  GENDER_PREF_ID   VARCHAR(50) NOT NULL COMMENT '파트너성별ID',
  AGE_PREF_ID      VARCHAR(50) NOT NULL COMMENT '파트너 연령ID',
  WORKTYPE_PREF_ID VARCHAR(50) NOT NULL COMMENT '근무형태ID',
  JOBTYPE_PREF_ID  VARCHAR(50) NOT NULL COMMENT '고용형태_ID',
  PAT_AREA_ID      VARCHAR(50) NOT NULL COMMENT '환자지역ID',
  CAR_LIC_PREF_ID  VARCHAR(50) NOT NULL COMMENT '차량/면허 여부 ID',
  CERT_PREF_ID     VARCHAR(50) NOT NULL COMMENT '자격증 소유 여부 ID',
  MEMBERID         VARCHAR(50) NOT NULL COMMENT '회원아이디',
  GENDER_ID        VARCHAR(50) NULL     COMMENT '성별ID',
  PATIENTGENDER_ID VARCHAR(50) NULL     COMMENT '환자성별ID',
  LEVEL_ID         VARCHAR(50) NOT NULL COMMENT '치매진행단계ID'
) COMMENT '설문A 결과';

CREATE TABLE MEMBER_F
(
  MEMBERID         VARCHAR(50) NOT NULL COMMENT '회원아이디',
  PATIENTGENDER_ID VARCHAR(50) NOT NULL COMMENT '환자성별ID',
  LEVEL_ID         VARCHAR(50) NOT NULL COMMENT '치매진행단계ID'
) COMMENT '가족';

CREATE TABLE MEMBER_S
(
  LEVEL_ID VARCHAR(50) NOT NULL COMMENT '치매진행단계ID',
  MEMBERID VARCHAR(50) NOT NULL COMMENT '회원아이디'
) COMMENT '본인';

CREATE TABLE MEMBERS
(
  PHOTO        VARCHAR(500) NOT NULL COMMENT '회원 사진',
  TYPE_ID      VARCHAR(50)  NOT NULL COMMENT '회원유형ID',
  MEMBERID     VARCHAR(50)  NOT NULL COMMENT '회원아이디',
  PASSWORD     VARCHAR(50)  NOT NULL COMMENT '비밀번호',
  NAME         VARCHAR(50)  NOT NULL COMMENT '이름',
  GENDER_ID    VARCHAR(50)  NOT NULL COMMENT '성별ID',
  BIRTHDATE    INTEGER(50)  NOT NULL COMMENT '생년월일',
  PHONENUMBER  INTEGER(50)  NOT NULL COMMENT '전화번호',
  ADDRESS      VARCHAR(500) NOT NULL COMMENT '주소',
  EMAIL        VARCHAR(50)  NOT NULL COMMENT '이메일',
  INTRODUCTION VARCHAR(500) NOT NULL COMMENT '자기소개',
  PRIMARY KEY (MEMBERID)
) COMMENT '회원DB';

CREATE TABLE PAT_AREA
(
  PAT_AREA    VARCHAR(50) NOT NULL COMMENT '지역',
  PAT_AREA_ID VARCHAR(50) NOT NULL COMMENT '지역ID',
  PRIMARY KEY (PAT_AREA_ID)
) COMMENT '환자 지역';

CREATE TABLE PATIENTGENDER
(
  PATIENTGENDER    VARCHAR(50) NOT NULL COMMENT '환자성별',
  PATIENTGENDER_ID VARCHAR(50) NOT NULL COMMENT '환자성별ID',
  PRIMARY KEY (PATIENTGENDER_ID)
) COMMENT '환자성별';

CREATE TABLE WORKTYPE_PREFER
(
  WORKTYPE_PREF    VARCHAR(50) NOT NULL COMMENT '근무형태',
  WORKTYPE_PREF_ID VARCHAR(50) NOT NULL COMMENT '근무형태ID',
  PRIMARY KEY (WORKTYPE_PREF_ID)
) COMMENT '근무형태 선호';

ALTER TABLE MATCHING_A
  ADD CONSTRAINT FK_GENDER_PREFER_TO_MATCHING_A
    FOREIGN KEY (GENDER_PREF_ID)
    REFERENCES GENDER_PREFER (GENDER_PREF_ID);

ALTER TABLE MATCHING_A
  ADD CONSTRAINT FK_AGE_PREFER_TO_MATCHING_A
    FOREIGN KEY (AGE_PREF_ID)
    REFERENCES AGE_PREFER (AGE_PREF_ID);

ALTER TABLE MATCHING_A
  ADD CONSTRAINT FK_WORKTYPE_PREFER_TO_MATCHING_A
    FOREIGN KEY (WORKTYPE_PREF_ID)
    REFERENCES WORKTYPE_PREFER (WORKTYPE_PREF_ID);

ALTER TABLE MATCHING_A
  ADD CONSTRAINT FK_JOBTYPE_PREFER_TO_MATCHING_A
    FOREIGN KEY (JOBTYPE_PREF_ID)
    REFERENCES JOBTYPE_PREFER (JOBTYPE_PREF_ID);

ALTER TABLE MATCHING_A
  ADD CONSTRAINT FK_PAT_AREA_TO_MATCHING_A
    FOREIGN KEY (PAT_AREA_ID)
    REFERENCES PAT_AREA (PAT_AREA_ID);

ALTER TABLE MATCHING_A
  ADD CONSTRAINT FK_CAR_LICENCE_PREFER_TO_MATCHING_A
    FOREIGN KEY (CAR_LIC_PREF_ID)
    REFERENCES CAR_LICENCE_PREFER (CAR_LIC_PREF_ID);

ALTER TABLE MATCHING_A
  ADD CONSTRAINT FK_CERTIFICATION_PREFER_TO_MATCHING_A
    FOREIGN KEY (CERT_PREF_ID)
    REFERENCES CERTIFICATION_PREFER (CERT_PREF_ID);

ALTER TABLE MATCHING_A
  ADD CONSTRAINT FK_MEMBERS_TO_MATCHING_A
    FOREIGN KEY (MEMBERID)
    REFERENCES MEMBERS (MEMBERID);

ALTER TABLE MATCHING_A
  ADD CONSTRAINT FK_GENDER_TO_MATCHING_A
    FOREIGN KEY (GENDER_ID)
    REFERENCES GENDER (GENDER_ID);

ALTER TABLE MEMBER_S
  ADD CONSTRAINT FK_LEVEL_TO_MEMBER_S
    FOREIGN KEY (LEVEL_ID)
    REFERENCES LEVEL (LEVEL_ID);

ALTER TABLE MEMBER_S
  ADD CONSTRAINT FK_MEMBERS_TO_MEMBER_S
    FOREIGN KEY (MEMBERID)
    REFERENCES MEMBERS (MEMBERID);

ALTER TABLE MEMBER_F
  ADD CONSTRAINT FK_PATIENTGENDER_TO_MEMBER_F
    FOREIGN KEY (PATIENTGENDER_ID)
    REFERENCES PATIENTGENDER (PATIENTGENDER_ID);

ALTER TABLE MEMBER_F
  ADD CONSTRAINT FK_LEVEL_TO_MEMBER_F
    FOREIGN KEY (LEVEL_ID)
    REFERENCES LEVEL (LEVEL_ID);

ALTER TABLE MEMBER_F
  ADD CONSTRAINT FK_MEMBERS_TO_MEMBER_F
    FOREIGN KEY (MEMBERID)
    REFERENCES MEMBERS (MEMBERID);

ALTER TABLE MATCHING_A
  ADD CONSTRAINT FK_PATIENTGENDER_TO_MATCHING_A
    FOREIGN KEY (PATIENTGENDER_ID)
    REFERENCES PATIENTGENDER (PATIENTGENDER_ID);

ALTER TABLE MATCHING_A
  ADD CONSTRAINT FK_LEVEL_TO_MATCHING_A
    FOREIGN KEY (LEVEL_ID)
    REFERENCES LEVEL (LEVEL_ID);
