
CREATE TABLE CAR_LICENCE
(
  CAR_LICENCE    VARCHAR(50) NOT NULL COMMENT '차량/면허 여부',
  CAR_LICENCE_ID VARCHAR(50) NOT NULL COMMENT '차량/면허 여부 ID',
  PRIMARY KEY (CAR_LICENCE_ID)
) COMMENT '차량/면허 여부';

CREATE TABLE CARE_LEVEL
(
  CARE_LEVEL    VARCHAR(50) NOT NULL COMMENT '치매케어단계',
  CARE_LEVEL_ID VARCHAR(50) NOT NULL COMMENT '치매케어단계 ID',
  PRIMARY KEY (CARE_LEVEL_ID)
) COMMENT '치매 케어 가능 단계';

CREATE TABLE CERTIFICATION
(
  CERTIFICATION    VARCHAR(50) NOT NULL COMMENT '자격증 소유 여부',
  CERTIFICATION_ID VARCHAR(50) NOT NULL COMMENT '자격증 소유 여부 ID',
  PRIMARY KEY (CERTIFICATION_ID)
) COMMENT '자격증 소유 여부';

CREATE TABLE GENDER
(
  GENDER    VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_ID VARCHAR(50) NOT NULL COMMENT '성별ID',
  PRIMARY KEY (GENDER_ID)
) COMMENT '성별';

CREATE TABLE JOBTYPE
(
  JOBTYPE    VARCHAR(50) NOT NULL COMMENT '고용형태',
  JOBTYPE_ID VARCHAR(50) NOT NULL COMMENT '고용형태_ID',
  PRIMARY KEY (JOBTYPE_ID)
) COMMENT '고용형태';

CREATE TABLE MATCHING_B
(
  PAT_GENDER_PREF_ID VARCHAR(50) NOT NULL COMMENT '환자성별선호ID',
  WORKTYPE_ID        VARCHAR(50) NOT NULL COMMENT '근무형태ID',
  JOBTYPE_ID         VARCHAR(50) NOT NULL COMMENT '고용형태_ID',
  CARE_LEVEL_ID      VARCHAR(50) NOT NULL COMMENT '치매케어단계 ID',
  AREA_FIRST_ID      VARCHAR(50) NOT NULL COMMENT '서비스지역1ID',
  AREA_SECOND_ID     VARCHAR(50) NOT NULL COMMENT '서비스지역2ID',
  CAR_LICENCE_ID     VARCHAR(50) NOT NULL COMMENT '차량/면허 여부 ID',
  CERTIFICATION_ID   VARCHAR(50) NOT NULL COMMENT '자격증 소유 여부 ID',
  GENDER_ID          VARCHAR(50) NOT NULL COMMENT '성별ID',
  MEMBERID           VARCHAR(50) NOT NULL COMMENT '회원아이디',
  BIRTHDATE          INTEGER(50) NOT NULL COMMENT '생년월일'
) COMMENT '설문B 결과';

CREATE TABLE MEMBERS
(
  PHOTO        VARCHAR(500) NOT NULL COMMENT '회원 사진',
  TYPE_ID      VARCHAR(50)  NOT NULL COMMENT '회원유형ID',
  MEMBERID     VARCHAR(50)  NOT NULL COMMENT '회원아이디',
  PASSWORD     VARCHAR(50)  NOT NULL COMMENT '비밀번호',
  NAME         VARCHAR(50)  NOT NULL COMMENT '이름',
  BIRTHDATE    INTEGER(50)  NOT NULL COMMENT '생년월일',
  PHONENUMBER  INTEGER(50)  NOT NULL COMMENT '전화번호',
  ADDRESS      VARCHAR(500) NOT NULL COMMENT '주소',
  EMAIL        VARCHAR(50)  NOT NULL COMMENT '이메일',
  INTRODUCTION VARCHAR(500) NOT NULL COMMENT '자기소개',
  GENDER_ID    VARCHAR(50)  NOT NULL COMMENT '성별ID',
  PRIMARY KEY (MEMBERID, BIRTHDATE)
) COMMENT '회원DB';

CREATE TABLE PAT_GENDER_PREF
(
  PAT_GENDER_PREF    VARCHAR(50) NOT NULL COMMENT '환자성별선호',
  PAT_GENDER_PREF_ID VARCHAR(50) NOT NULL COMMENT '환자성별선호ID',
  PRIMARY KEY (PAT_GENDER_PREF_ID)
) COMMENT '선호 환자 성별';

CREATE TABLE SERVICEAREA_FIRST
(
  AREA_FIRST    VARCHAR(50) NOT NULL COMMENT '서비스지역1',
  AREA_FIRST_ID VARCHAR(50) NOT NULL COMMENT '서비스지역1ID',
  PRIMARY KEY (AREA_FIRST_ID)
) COMMENT '서비스 지역 1';

CREATE TABLE SERVICEAREA_SECOND
(
  AREA_SECOND    VARCHAR(50) NOT NULL COMMENT '서비스지역2',
  AREA_SECOND_ID VARCHAR(50) NOT NULL COMMENT '서비스지역2ID',
  PRIMARY KEY (AREA_SECOND_ID)
) COMMENT '서비스 지역 1';

CREATE TABLE WORKTYPE
(
  WORKTYPE    VARCHAR(50) NOT NULL COMMENT '근무형태',
  WORKTYPE_ID VARCHAR(50) NOT NULL COMMENT '근무형태ID',
  PRIMARY KEY (WORKTYPE_ID)
) COMMENT '근무형태';

ALTER TABLE MATCHING_B
  ADD CONSTRAINT FK_PAT_GENDER_PREF_TO_MATCHING_B
    FOREIGN KEY (PAT_GENDER_PREF_ID)
    REFERENCES PAT_GENDER_PREF (PAT_GENDER_PREF_ID);

ALTER TABLE MATCHING_B
  ADD CONSTRAINT FK_WORKTYPE_TO_MATCHING_B
    FOREIGN KEY (WORKTYPE_ID)
    REFERENCES WORKTYPE (WORKTYPE_ID);

ALTER TABLE MATCHING_B
  ADD CONSTRAINT FK_JOBTYPE_TO_MATCHING_B
    FOREIGN KEY (JOBTYPE_ID)
    REFERENCES JOBTYPE (JOBTYPE_ID);

ALTER TABLE MATCHING_B
  ADD CONSTRAINT FK_SERVICEAREA_FIRST_TO_MATCHING_B
    FOREIGN KEY (AREA_FIRST_ID)
    REFERENCES SERVICEAREA_FIRST (AREA_FIRST_ID);

ALTER TABLE MATCHING_B
  ADD CONSTRAINT FK_CARE_LEVEL_TO_MATCHING_B
    FOREIGN KEY (CARE_LEVEL_ID)
    REFERENCES CARE_LEVEL (CARE_LEVEL_ID);

ALTER TABLE MATCHING_B
  ADD CONSTRAINT FK_SERVICEAREA_SECOND_TO_MATCHING_B
    FOREIGN KEY (AREA_SECOND_ID)
    REFERENCES SERVICEAREA_SECOND (AREA_SECOND_ID);

ALTER TABLE MEMBERS
  ADD CONSTRAINT FK_GENDER_TO_MEMBERS
    FOREIGN KEY (GENDER_ID)
    REFERENCES GENDER (GENDER_ID);

ALTER TABLE MATCHING_B
  ADD CONSTRAINT FK_CAR_LICENCE_TO_MATCHING_B
    FOREIGN KEY (CAR_LICENCE_ID)
    REFERENCES CAR_LICENCE (CAR_LICENCE_ID);

ALTER TABLE MATCHING_B
  ADD CONSTRAINT FK_CERTIFICATION_TO_MATCHING_B
    FOREIGN KEY (CERTIFICATION_ID)
    REFERENCES CERTIFICATION (CERTIFICATION_ID);

ALTER TABLE MATCHING_B
  ADD CONSTRAINT FK_GENDER_TO_MATCHING_B
    FOREIGN KEY (GENDER_ID)
    REFERENCES GENDER (GENDER_ID);

ALTER TABLE MATCHING_B
  ADD CONSTRAINT FK_MEMBERS_TO_MATCHING_B
    FOREIGN KEY (MEMBERID, BIRTHDATE)
    REFERENCES MEMBERS (MEMBERID, BIRTHDATE);
