
CREATE TABLE A_Questions_Code
(
  A_QUESTIONS    VARCHAR(500) NOT NULL COMMENT '질문내용',
  A_QUESTIONS_ID VARCHAR(50)  NOT NULL COMMENT '질문아이디',
  PRIMARY KEY (A_QUESTIONS_ID)
) COMMENT '환자/가족 질문 코드';

CREATE TABLE AQ_01_ANSWER_CODE
(
  AQ_01_ANSWERS    VARCHAR(50) NOT NULL COMMENT '질문 1 답 종류',
  AQ_01_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 1 답 코드',
  PRIMARY KEY (AQ_01_ANSWERS_ID)
) COMMENT '1. 파트너 성별에 대한 답';

CREATE TABLE AQ_01_QNA
(
  A_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  AQ_01_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 1 답 코드'
) COMMENT '질문과 답 AQ01';

CREATE TABLE AQ_02_ANSWER_CODE
(
  AQ_02_ANSWERS    VARCHAR(50) NOT NULL COMMENT '질문 2 답 종류',
  AQ_02_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 2 답 코드',
  PRIMARY KEY (AQ_02_ANSWERS_ID)
) COMMENT '2. 파트너 연령에 대한 답';

CREATE TABLE AQ_02_QNA
(
  A_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  AQ_02_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 2 답 코드'
);

CREATE TABLE AQ_03_ANSWER_CODE
(
  AQ_03_ANSWERS    VARCHAR(50) NOT NULL COMMENT '질문 3 답 종류',
  AQ_03_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 3 답 코드',
  PRIMARY KEY (AQ_03_ANSWERS_ID)
) COMMENT '3. 근무형태에 대한 답';

CREATE TABLE AQ_03_QNA
(
  A_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  AQ_03_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 3 답 코드'
);

CREATE TABLE AQ_04_ANSWER_CODE
(
  AQ_04_ANSWERS    VARCHAR(50) NOT NULL,
  AQ_04_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 4 답 코드',
  PRIMARY KEY (AQ_04_ANSWERS_ID)
) COMMENT '4. 고용형태에 대한 답';

CREATE TABLE AQ_04_QNA
(
  A_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  AQ_04_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 4 답 코드'
);

CREATE TABLE AQ_05_ANSWER_CODE
(
  AQ_05_ANSWERS    VARCHAR(50) NOT NULL,
  AQ_05_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 5 답 코드',
  PRIMARY KEY (AQ_05_ANSWERS_ID)
) COMMENT '5. 서비스지역에 대한 답';

CREATE TABLE AQ_05_QNA
(
  A_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  AQ_05_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 5 답 코드'
);

CREATE TABLE AQ_06_ANSWER_CODE
(
  AQ_06_ANSWERS    VARCHAR(50) NOT NULL,
  AQ_06_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 6 답 코드',
  PRIMARY KEY (AQ_06_ANSWERS_ID)
) COMMENT '6. 차량/면허에 대한 답';

CREATE TABLE AQ_06_QNA
(
  A_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  AQ_06_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 6 답 코드'
);

CREATE TABLE AQ_07_ANSWER_CODE
(
  AQ_07_ANSWERS    VARCHAR(50) NOT NULL,
  AQ_07_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 7 답 코드',
  PRIMARY KEY (AQ_07_ANSWERS_ID)
) COMMENT '7. 자격증에 대한 답';

CREATE TABLE AQ_07_QNA
(
  A_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  AQ_07_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 7 답 코드'
);

ALTER TABLE AQ_01_QNA
  ADD CONSTRAINT FK_A_Questions_Code_TO_AQ_01_QNA
    FOREIGN KEY (A_QUESTIONS_ID)
    REFERENCES A_Questions_Code (A_QUESTIONS_ID);

ALTER TABLE AQ_01_QNA
  ADD CONSTRAINT FK_AQ_01_ANSWER_CODE_TO_AQ_01_QNA
    FOREIGN KEY (AQ_01_ANSWERS_ID)
    REFERENCES AQ_01_ANSWER_CODE (AQ_01_ANSWERS_ID);

ALTER TABLE AQ_02_QNA
  ADD CONSTRAINT FK_A_Questions_Code_TO_AQ_02_QNA
    FOREIGN KEY (A_QUESTIONS_ID)
    REFERENCES A_Questions_Code (A_QUESTIONS_ID);

ALTER TABLE AQ_02_QNA
  ADD CONSTRAINT FK_AQ_02_ANSWER_CODE_TO_AQ_02_QNA
    FOREIGN KEY (AQ_02_ANSWERS_ID)
    REFERENCES AQ_02_ANSWER_CODE (AQ_02_ANSWERS_ID);

ALTER TABLE AQ_03_QNA
  ADD CONSTRAINT FK_A_Questions_Code_TO_AQ_03_QNA
    FOREIGN KEY (A_QUESTIONS_ID)
    REFERENCES A_Questions_Code (A_QUESTIONS_ID);

ALTER TABLE AQ_03_QNA
  ADD CONSTRAINT FK_AQ_03_ANSWER_CODE_TO_AQ_03_QNA
    FOREIGN KEY (AQ_03_ANSWERS_ID)
    REFERENCES AQ_03_ANSWER_CODE (AQ_03_ANSWERS_ID);

ALTER TABLE AQ_04_QNA
  ADD CONSTRAINT FK_A_Questions_Code_TO_AQ_04_QNA
    FOREIGN KEY (A_QUESTIONS_ID)
    REFERENCES A_Questions_Code (A_QUESTIONS_ID);

ALTER TABLE AQ_04_QNA
  ADD CONSTRAINT FK_AQ_04_ANSWER_CODE_TO_AQ_04_QNA
    FOREIGN KEY (AQ_04_ANSWERS_ID)
    REFERENCES AQ_04_ANSWER_CODE (AQ_04_ANSWERS_ID);

ALTER TABLE AQ_05_QNA
  ADD CONSTRAINT FK_A_Questions_Code_TO_AQ_05_QNA
    FOREIGN KEY (A_QUESTIONS_ID)
    REFERENCES A_Questions_Code (A_QUESTIONS_ID);

ALTER TABLE AQ_05_QNA
  ADD CONSTRAINT FK_AQ_05_ANSWER_CODE_TO_AQ_05_QNA
    FOREIGN KEY (AQ_05_ANSWERS_ID)
    REFERENCES AQ_05_ANSWER_CODE (AQ_05_ANSWERS_ID);

ALTER TABLE AQ_06_QNA
  ADD CONSTRAINT FK_A_Questions_Code_TO_AQ_06_QNA
    FOREIGN KEY (A_QUESTIONS_ID)
    REFERENCES A_Questions_Code (A_QUESTIONS_ID);

ALTER TABLE AQ_06_QNA
  ADD CONSTRAINT FK_AQ_06_ANSWER_CODE_TO_AQ_06_QNA
    FOREIGN KEY (AQ_06_ANSWERS_ID)
    REFERENCES AQ_06_ANSWER_CODE (AQ_06_ANSWERS_ID);

ALTER TABLE AQ_07_QNA
  ADD CONSTRAINT FK_A_Questions_Code_TO_AQ_07_QNA
    FOREIGN KEY (A_QUESTIONS_ID)
    REFERENCES A_Questions_Code (A_QUESTIONS_ID);

ALTER TABLE AQ_07_QNA
  ADD CONSTRAINT FK_AQ_07_ANSWER_CODE_TO_AQ_07_QNA
    FOREIGN KEY (AQ_07_ANSWERS_ID)
    REFERENCES AQ_07_ANSWER_CODE (AQ_07_ANSWERS_ID);
