-- SURVEY_TYPE 설문 A, B 타입 코드 데이터 삽입
INSERT INTO SURVEY_TYPE (SURVEY_TYPE, SURVEY_TYPE_ID) VALUES ('환자 및 가족 설문', 'SUSURVEY_TYPE_IDsurvey_typeR-A');
INSERT INTO SURVEY_TYPE (SURVEY_TYPE, SURVEY_TYPE_ID) VALUES ('파트너 설문', 'SUR-B');

-- SURVEY_QUESTIONS 설문 A 질문 코드 데이터 삽입
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('선호하는 파트너의 성별이 있나요?', 'SUR-A', 'SURQ01');
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('선호하는 파트너의 연령이 있나요?', 'SUR-A', 'SURQ02');
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('어떤 근무 형태를 원하시나요?', 'SUR-A', 'SURQ03');
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('원하시는 고용형태는요?', 'SUR-A', 'SURQ04');
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('서비스를 받고 싶은 지역을 선택해주세요', 'SUR-A', 'SURQ05');
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('차량 또는 면허가 필요할까요?', 'SUR-A', 'SURQ06');
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('자격증이 필요한가요?', 'SUR-A', 'SURQ07');

-- SURVEY_QUESTIONS 설문 B 질문 코드 데이터 삽입
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('선호하는 환자의 성별이 있나요?', 'SUR-B', 'SURQ08');
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('어떤 근무 형태를 원하시나요?', 'SUR-B', 'SURQ09');
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('원하시는 고용형태는요?', 'SUR-B', 'SURQ10');
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('동행 가능한 환자의 치매 단계는 어떻게 될까요?', 'SUR-B', 'SURQ11');
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('선호하는 지역을 선택해주세요(1순위)', 'SUR-B', 'SURQ12');
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('선호하는 지역을 선택해주세요(2순위)', 'SUR-B', 'SURQ13');
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('차량 또는 면허가 있나요?', 'SUR-B', 'SURQ14');
INSERT INTO SURVEY_QUESTIONS (SURVEY_Q, SURVEY_TYPE_ID, SURVEY_Q_ID) VALUES ('자격증이 있나요?', 'SUR-B', 'SURQ15');

-- SURVEY_QNA 설문 A 답변 코드 데이터 삽입
