
CREATE TABLE MEMBERS
(
  PHOTO        VARCHAR(500) NOT NULL COMMENT '회원 사진',
  TYPE_ID      VARCHAR(50)  NOT NULL COMMENT '회원유형ID',
  MEMBERID     VARCHAR(50)  NOT NULL COMMENT '회원아이디',
  PASSWORD     VARCHAR(50)  NOT NULL COMMENT '비밀번호',
  NAME         VARCHAR(50)  NOT NULL COMMENT '이름',
  GENDER_ID    VARCHAR(50)  NOT NULL COMMENT '성별ID',
  BIRTHDATE    INTEGER(50)  NOT NULL COMMENT '생년월일',
  PHONENUMBER  INTEGER(50)  NOT NULL COMMENT '전화번호',
  ADDRESS      VARCHAR(500) NOT NULL COMMENT '주소',
  EMAIL        VARCHAR(50)  NOT NULL COMMENT '이메일',
  INTRODUCTION VARCHAR(500) NOT NULL COMMENT '자기소개',
  PRIMARY KEY (MEMBERID)
) COMMENT '회원DB';

CREATE TABLE PAGE
(
  COMMENT    VARCHAR(500) NOT NULL COMMENT '댓글내용',
  DATE       VARCHAR(50)  NOT NULL COMMENT '작성일자',
  MEMBERID   VARCHAR(50)  NOT NULL COMMENT '사용자ID',
  POST_ID    VARCHAR(50)  NOT NULL COMMENT '게시글ID',
  COMMENT_ID VARCHAR(50)  NOT NULL COMMENT '댓글ID',
  PRIMARY KEY (COMMENT_ID)
) COMMENT '게시글+댓글 페이지';

CREATE TABLE POST
(
  TITLE    VARCHAR(50)  NOT NULL COMMENT '제목',
  DATE     VARCHAR(50)  NOT NULL COMMENT '작성일자',
  CONTENT  VARCHAR(500) NOT NULL COMMENT '내용',
  MEMBERID VARCHAR(50)  NOT NULL COMMENT '사용자ID',
  POST_ID  VARCHAR(50)  NOT NULL COMMENT '게시글ID',
  PRIMARY KEY (POST_ID)
) COMMENT '게시글';

ALTER TABLE PAGE
  ADD CONSTRAINT FK_MEMBERS_TO_PAGE
    FOREIGN KEY (MEMBERID)
    REFERENCES MEMBERS (MEMBERID);

ALTER TABLE PAGE
  ADD CONSTRAINT FK_POST_TO_PAGE
    FOREIGN KEY (POST_ID)
    REFERENCES POST (POST_ID);

ALTER TABLE POST
  ADD CONSTRAINT FK_MEMBERS_TO_POST
    FOREIGN KEY (MEMBERID)
    REFERENCES MEMBERS (MEMBERID);
