
CREATE TABLE GENDER
(
  GENDER    VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_ID VARCHAR(50) NOT NULL COMMENT '성별ID',
  PRIMARY KEY (GENDER_ID)
) COMMENT '성별';

CREATE TABLE MEMBER_P
(
  PHOTO        VARCHAR(500) NOT NULL COMMENT '회원 사진',
  TYPE_ID      VARCHAR(50)  NOT NULL COMMENT '회원유형ID',
  MEMBERID     VARCHAR(50)  NOT NULL COMMENT '회원아이디',
  PASSWORD     VARCHAR(50)  NOT NULL COMMENT '비밀번호',
  NAME         VARCHAR(50)  NOT NULL COMMENT '이름',
  GENDER_ID    VARCHAR(50)  NOT NULL COMMENT '성별ID',
  BIRTHDATE    INTEGER(50)  NOT NULL COMMENT '생년월일',
  PHONENUMBER  INTEGER(50)  NOT NULL COMMENT '전화번호',
  ADDRESS      VARCHAR(500) NOT NULL COMMENT '주소',
  EMAIL        VARCHAR(50)  NOT NULL COMMENT '이메일',
  INTRODUCTION VARCHAR(500) NOT NULL COMMENT '자기소개'
) COMMENT '파트너회원DB';

CREATE TABLE TYPE
(
  TYPE    VARCHAR(50) NOT NULL COMMENT '회원유형',
  TYPE_ID VARCHAR(50) NOT NULL COMMENT '회원유형ID',
  PRIMARY KEY (TYPE_ID)
) COMMENT '회원유형';

ALTER TABLE MEMBER_P
  ADD CONSTRAINT FK_TYPE_TO_MEMBER_P
    FOREIGN KEY (TYPE_ID)
    REFERENCES TYPE (TYPE_ID);

ALTER TABLE MEMBER_P
  ADD CONSTRAINT FK_GENDER_TO_MEMBER_P
    FOREIGN KEY (GENDER_ID)
    REFERENCES GENDER (GENDER_ID);
