
CREATE TABLE ANS_CODE
(
  ANSWERS   VARCHAR(50) NOT NULL COMMENT '답변 종류',
  ANS_SCORE INTEGER     NOT NULL COMMENT '답변 점수',
  PRIMARY KEY (ANS_SCORE)
) COMMENT '답변 코드';

CREATE TABLE MEMBERS
(
  PHOTO        VARCHAR(500) NOT NULL COMMENT '회원 사진',
  TYPE_ID      VARCHAR(50)  NOT NULL COMMENT '회원유형ID',
  MEMBERID     VARCHAR(50)  NOT NULL COMMENT '회원아이디',
  PASSWORD     VARCHAR(50)  NOT NULL COMMENT '비밀번호',
  NAME         VARCHAR(50)  NOT NULL COMMENT '이름',
  GENDER_ID    VARCHAR(50)  NOT NULL COMMENT '성별ID',
  BIRTHDATE    INTEGER(50)  NOT NULL COMMENT '생년월일',
  PHONENUMBER  INTEGER(50)  NOT NULL COMMENT '전화번호',
  ADDRESS      VARCHAR(500) NOT NULL COMMENT '주소',
  EMAIL        VARCHAR(50)  NOT NULL COMMENT '이메일',
  INTRODUCTION VARCHAR(500) NOT NULL COMMENT '자기소개',
  PRIMARY KEY (MEMBERID)
) COMMENT '회원DB';

CREATE TABLE Q_CODE
(
  QUESTIONS VARCHAR(500) NOT NULL COMMENT '자가진단 질문',
  Q_CODE    VARCHAR(50)  NOT NULL COMMENT '질문 코드',
  PRIMARY KEY (Q_CODE)
) COMMENT '질문 코드';

CREATE TABLE QNA
(
  Q_CODE    VARCHAR(50) NOT NULL COMMENT '질문 코드',
  ANS_SCORE INTEGER     NOT NULL COMMENT '답변 점수',
  QNA_CODE  VARCHAR(50) NOT NULL COMMENT '질답 코드',
  PRIMARY KEY (QNA_CODE)
) COMMENT '자가진단 메인 화면';

CREATE TABLE 답변한내역
(
  QNA_CODE VARCHAR(50) NOT NULL,
  MEMBERID VARCHAR(50) NOT NULL COMMENT '회원아이디'
);

ALTER TABLE QNA
  ADD CONSTRAINT FK_Q_CODE_TO_QNA
    FOREIGN KEY (Q_CODE)
    REFERENCES Q_CODE (Q_CODE);

ALTER TABLE QNA
  ADD CONSTRAINT FK_ANS_CODE_TO_QNA
    FOREIGN KEY (ANS_SCORE)
    REFERENCES ANS_CODE (ANS_SCORE);

ALTER TABLE 답변한내역
  ADD CONSTRAINT FK_QNA_TO_답변한내역
    FOREIGN KEY (QNA_CODE)
    REFERENCES QNA (QNA_CODE);

ALTER TABLE 답변한내역
  ADD CONSTRAINT FK_MEMBERS_TO_답변한내역
    FOREIGN KEY (MEMBERID)
    REFERENCES MEMBERS (MEMBERID);
