
CREATE TABLE B_Questions_Code
(
  B_QUESTIONS    VARCHAR(500) NOT NULL COMMENT '질문내용',
  B_QUESTIONS_ID VARCHAR(50)  NOT NULL COMMENT '질문아이디',
  PRIMARY KEY (B_QUESTIONS_ID)
) COMMENT '파트너 질문 코드';

CREATE TABLE BQ_01_ANSWER_CODE
(
  BQ_01_ANSWERS    VARCHAR(50) NOT NULL COMMENT '질문 1 답 종류',
  BQ_01_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 1 답 코드',
  PRIMARY KEY (BQ_01_ANSWERS_ID)
) COMMENT '1. 환자 성별에 대한 답';

CREATE TABLE BQ_01_QNA
(
  B_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  BQ_01_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 1 답 코드'
) COMMENT '질문과 답 BQ01';

CREATE TABLE BQ_02_ANSWER_CODE
(
  BQ_02_ANSWERS    VARCHAR(50) NOT NULL COMMENT '질문 2 답 종류',
  BQ_02_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 2 답 코드',
  PRIMARY KEY (BQ_02_ANSWERS_ID)
) COMMENT '2. 근무형태에 대한 답';

CREATE TABLE BQ_02_QNA
(
  B_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  BQ_02_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 2 답 코드'
) COMMENT '질문과 답 BQ02';

CREATE TABLE BQ_03_ANSWER_CODE
(
  BQ_03_ANSWERS    VARCHAR(50) NOT NULL COMMENT '질문 3 답 종류',
  BQ_03_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 3 답 코드',
  PRIMARY KEY (BQ_03_ANSWERS_ID)
) COMMENT '3. 고용형태에 대한 답';

CREATE TABLE BQ_03_QNA
(
  B_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  BQ_03_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 3 답 코드'
) COMMENT '질문과 답 BQ03';

CREATE TABLE BQ_04_ANSWER_CODE
(
  BQ_04_ANSWERS    VARCHAR(50) NOT NULL,
  BQ_04_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 4 답 코드',
  PRIMARY KEY (BQ_04_ANSWERS_ID)
) COMMENT '4. 치매단계에 대한 답';

CREATE TABLE BQ_04_QNA
(
  B_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  BQ_04_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 4 답 코드'
) COMMENT '질문과 답 BQ04';

CREATE TABLE BQ_05_ANSWER_CODE
(
  BQ_05_ANSWERS    VARCHAR(50) NOT NULL,
  BQ_05_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 5 답 코드',
  PRIMARY KEY (BQ_05_ANSWERS_ID)
) COMMENT '5. 서비스지역1 에 대한 답';

CREATE TABLE BQ_05_QNA
(
  B_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  BQ_05_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 5 답 코드'
) COMMENT '질문과 답 BQ05';

CREATE TABLE BQ_06_ANSWER_CODE
(
  BQ_06_ANSWERS    VARCHAR(50) NOT NULL,
  BQ_06_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 6 답 코드',
  PRIMARY KEY (BQ_06_ANSWERS_ID)
) COMMENT '6. 서비스지역2에 대한 답';

CREATE TABLE BQ_06_QNA
(
  B_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  BQ_06_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 6 답 코드'
) COMMENT '질문과 답 BQ06';

CREATE TABLE BQ_07_ANSWER_CODE
(
  BQ_07_ANSWERS    VARCHAR(50) NOT NULL,
  BQ_07_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 7 답 코드',
  PRIMARY KEY (BQ_07_ANSWERS_ID)
) COMMENT '7. 차량/면허에 대한 답';

CREATE TABLE BQ_07_QNA
(
  B_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  BQ_07_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 7 답 코드'
) COMMENT '질문과 답 BQ07';

CREATE TABLE BQ_08_ANSWER_CODE
(
  BQ_08_ANSWERS    VARCHAR(50) NOT NULL,
  BQ_08_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 8 답 코드',
  PRIMARY KEY (BQ_08_ANSWERS_ID)
) COMMENT '8. 자격증에 대한 답';

CREATE TABLE BQ_08_QNA
(
  B_QUESTIONS_ID   VARCHAR(50) NOT NULL COMMENT '질문아이디',
  BQ_08_ANSWERS_ID VARCHAR(50) NOT NULL COMMENT '질문 8 답 코드'
) COMMENT '질문과 답 BQ08';

ALTER TABLE BQ_01_QNA
  ADD CONSTRAINT FK_B_Questions_Code_TO_BQ_01_QNA
    FOREIGN KEY (B_QUESTIONS_ID)
    REFERENCES B_Questions_Code (B_QUESTIONS_ID);

ALTER TABLE BQ_01_QNA
  ADD CONSTRAINT FK_BQ_01_ANSWER_CODE_TO_BQ_01_QNA
    FOREIGN KEY (BQ_01_ANSWERS_ID)
    REFERENCES BQ_01_ANSWER_CODE (BQ_01_ANSWERS_ID);

ALTER TABLE BQ_02_QNA
  ADD CONSTRAINT FK_B_Questions_Code_TO_BQ_02_QNA
    FOREIGN KEY (B_QUESTIONS_ID)
    REFERENCES B_Questions_Code (B_QUESTIONS_ID);

ALTER TABLE BQ_02_QNA
  ADD CONSTRAINT FK_BQ_02_ANSWER_CODE_TO_BQ_02_QNA
    FOREIGN KEY (BQ_02_ANSWERS_ID)
    REFERENCES BQ_02_ANSWER_CODE (BQ_02_ANSWERS_ID);

ALTER TABLE BQ_03_QNA
  ADD CONSTRAINT FK_B_Questions_Code_TO_BQ_03_QNA
    FOREIGN KEY (B_QUESTIONS_ID)
    REFERENCES B_Questions_Code (B_QUESTIONS_ID);

ALTER TABLE BQ_03_QNA
  ADD CONSTRAINT FK_BQ_03_ANSWER_CODE_TO_BQ_03_QNA
    FOREIGN KEY (BQ_03_ANSWERS_ID)
    REFERENCES BQ_03_ANSWER_CODE (BQ_03_ANSWERS_ID);

ALTER TABLE BQ_04_QNA
  ADD CONSTRAINT FK_B_Questions_Code_TO_BQ_04_QNA
    FOREIGN KEY (B_QUESTIONS_ID)
    REFERENCES B_Questions_Code (B_QUESTIONS_ID);

ALTER TABLE BQ_04_QNA
  ADD CONSTRAINT FK_BQ_04_ANSWER_CODE_TO_BQ_04_QNA
    FOREIGN KEY (BQ_04_ANSWERS_ID)
    REFERENCES BQ_04_ANSWER_CODE (BQ_04_ANSWERS_ID);

ALTER TABLE BQ_05_QNA
  ADD CONSTRAINT FK_B_Questions_Code_TO_BQ_05_QNA
    FOREIGN KEY (B_QUESTIONS_ID)
    REFERENCES B_Questions_Code (B_QUESTIONS_ID);

ALTER TABLE BQ_05_QNA
  ADD CONSTRAINT FK_BQ_05_ANSWER_CODE_TO_BQ_05_QNA
    FOREIGN KEY (BQ_05_ANSWERS_ID)
    REFERENCES BQ_05_ANSWER_CODE (BQ_05_ANSWERS_ID);

ALTER TABLE BQ_06_QNA
  ADD CONSTRAINT FK_B_Questions_Code_TO_BQ_06_QNA
    FOREIGN KEY (B_QUESTIONS_ID)
    REFERENCES B_Questions_Code (B_QUESTIONS_ID);

ALTER TABLE BQ_06_QNA
  ADD CONSTRAINT FK_BQ_06_ANSWER_CODE_TO_BQ_06_QNA
    FOREIGN KEY (BQ_06_ANSWERS_ID)
    REFERENCES BQ_06_ANSWER_CODE (BQ_06_ANSWERS_ID);

ALTER TABLE BQ_07_QNA
  ADD CONSTRAINT FK_B_Questions_Code_TO_BQ_07_QNA
    FOREIGN KEY (B_QUESTIONS_ID)
    REFERENCES B_Questions_Code (B_QUESTIONS_ID);

ALTER TABLE BQ_07_QNA
  ADD CONSTRAINT FK_BQ_07_ANSWER_CODE_TO_BQ_07_QNA
    FOREIGN KEY (BQ_07_ANSWERS_ID)
    REFERENCES BQ_07_ANSWER_CODE (BQ_07_ANSWERS_ID);

ALTER TABLE BQ_08_QNA
  ADD CONSTRAINT FK_B_Questions_Code_TO_BQ_08_QNA
    FOREIGN KEY (B_QUESTIONS_ID)
    REFERENCES B_Questions_Code (B_QUESTIONS_ID);

ALTER TABLE BQ_08_QNA
  ADD CONSTRAINT FK_BQ_08_ANSWER_CODE_TO_BQ_08_QNA
    FOREIGN KEY (BQ_08_ANSWERS_ID)
    REFERENCES BQ_08_ANSWER_CODE (BQ_08_ANSWERS_ID);
