
CREATE TABLE CAR&LICENSE
(
  CAR&LECENCE    VARCHAR(50) NOT NULL COMMENT '차량/면허 여부',
  CAR&LICENCE_ID VARCHAR(50) NOT NULL COMMENT '차량/면허 여부 ID',
  PRIMARY KEY (CAR&LICENCE_ID)
) COMMENT '차량/면허 여부';

CREATE TABLE CERTIFICATION
(
  CERTIFICATION    VARCHAR(50) NOT NULL COMMENT '자격증 소유 여부',
  CERTIFICATION_ID VARCHAR(50) NOT NULL COMMENT '자격증 소유 여부 ID',
  PRIMARY KEY (CERTIFICATION_ID)
) COMMENT '자격증 소유 여부';

CREATE TABLE JOBTYPE
(
  JOBTYPE    VARCHAR(50) NOT NULL COMMENT '고용형태',
  JOBTYPE_ID VARCHAR(50) NOT NULL COMMENT '고용형태_ID',
  PRIMARY KEY (JOBTYPE_ID)
) COMMENT '고용형태';

CREATE TABLE LEVEL
(
  LEVEL    VARCHAR(50) NOT NULL COMMENT '치매진행단계',
  LEVEL_ID VARCHAR(50) NOT NULL COMMENT '치매진행단계ID',
  PRIMARY KEY (LEVEL_ID)
) COMMENT '치매진행단계';

CREATE TABLE MATCHING_S&F
(
  MEMBERID         VARCHAR(50) NOT NULL COMMENT '회원아이디',
  PARTNERGENDER_ID VARCHAR(50) NOT NULL COMMENT '파트너성별ID',
  PARTNERAGE_ID    INTEGER(50) NOT NULL COMMENT '파트너 연령ID',
  WORKTYPE_ID      VARCHAR(50) NOT NULL COMMENT '근무형태ID',
  JOBTYPE_ID       VARCHAR(50) NOT NULL COMMENT '고용형태_ID',
  SERVICEAREA_ID   VARCHAR(50) NOT NULL COMMENT '서비스지역ID',
  CAR&LICENCE_ID   VARCHAR(50) NOT NULL COMMENT '차량/면허 여부 ID',
  CERTIFICATION_ID VARCHAR(50) NOT NULL COMMENT '자격증 소유 여부 ID'
) COMMENT '파트너 매칭_본인&가족';

CREATE TABLE MEMBERID
(
  MEMBERID         VARCHAR(50) NOT NULL COMMENT '회원아이디',
  TYPE_ID          VARCHAR(50) NOT NULL COMMENT '회원유형ID',
  PATIENTGENDER_ID VARCHAR(50) NOT NULL COMMENT '환자성별ID',
  LEVEL_ID         VARCHAR(50) NOT NULL COMMENT '치매진행단계ID',
  PRIMARY KEY (MEMBERID)
) COMMENT '회원아이디';

CREATE TABLE PARTNERAGE
(
  PARTNERAGE    INTEGER(50) NOT NULL COMMENT '파트너 연령',
  PARTNERAGE_ID INTEGER(50) NOT NULL COMMENT '파트너 연령ID',
  PRIMARY KEY (PARTNERAGE_ID)
) COMMENT '파트너 연령';

CREATE TABLE PARTNERGENDER
(
  PARTNERGENDER    VARCHAR(50) NOT NULL COMMENT '파트너성별',
  PARTNERGENDER_ID VARCHAR(50) NOT NULL COMMENT '파트너성별ID',
  PRIMARY KEY (PARTNERGENDER_ID)
) COMMENT '파트너 성별';

CREATE TABLE PATIENTGENDER
(
  PATIENTGENDER    VARCHAR(50) NOT NULL COMMENT '환자성별',
  PATIENTGENDER_ID VARCHAR(50) NOT NULL COMMENT '환자성별ID',
  PRIMARY KEY (PATIENTGENDER_ID)
) COMMENT '환자성별';

CREATE TABLE SERVICEAREA
(
  SERVICEAREA    VARCHAR(50) NOT NULL COMMENT '서비스지역',
  SERVICEAREA_ID VARCHAR(50) NOT NULL COMMENT '서비스지역ID',
  PRIMARY KEY (SERVICEAREA_ID)
) COMMENT '서비스 지역';

CREATE TABLE TYPE
(
  TYPE    VARCHAR(50) NOT NULL COMMENT '회원유형',
  TYPE_ID VARCHAR(50) NOT NULL COMMENT '회원유형ID',
  PRIMARY KEY (TYPE_ID)
) COMMENT '회원유형';

CREATE TABLE WORKTYPE
(
  WORKTYPE    VARCHAR(50) NOT NULL COMMENT '근무형태',
  WORKTYPE_ID VARCHAR(50) NOT NULL COMMENT '근무형태ID',
  PRIMARY KEY (WORKTYPE_ID)
) COMMENT '근무형태';

ALTER TABLE MATCHING_S&F
  ADD CONSTRAINT FK_MEMBERID_TO_MATCHING_S&F
    FOREIGN KEY (MEMBERID)
    REFERENCES MEMBERID (MEMBERID);

ALTER TABLE MEMBERID
  ADD CONSTRAINT FK_TYPE_TO_MEMBERID
    FOREIGN KEY (TYPE_ID)
    REFERENCES TYPE (TYPE_ID);

ALTER TABLE MEMBERID
  ADD CONSTRAINT FK_PATIENTGENDER_TO_MEMBERID
    FOREIGN KEY (PATIENTGENDER_ID)
    REFERENCES PATIENTGENDER (PATIENTGENDER_ID);

ALTER TABLE MEMBERID
  ADD CONSTRAINT FK_LEVEL_TO_MEMBERID
    FOREIGN KEY (LEVEL_ID)
    REFERENCES LEVEL (LEVEL_ID);

ALTER TABLE MATCHING_S&F
  ADD CONSTRAINT FK_PARTNERGENDER_TO_MATCHING_S&F
    FOREIGN KEY (PARTNERGENDER_ID)
    REFERENCES PARTNERGENDER (PARTNERGENDER_ID);

ALTER TABLE MATCHING_S&F
  ADD CONSTRAINT FK_PARTNERAGE_TO_MATCHING_S&F
    FOREIGN KEY (PARTNERAGE_ID)
    REFERENCES PARTNERAGE (PARTNERAGE_ID);

ALTER TABLE MATCHING_S&F
  ADD CONSTRAINT FK_WORKTYPE_TO_MATCHING_S&F
    FOREIGN KEY (WORKTYPE_ID)
    REFERENCES WORKTYPE (WORKTYPE_ID);

ALTER TABLE MATCHING_S&F
  ADD CONSTRAINT FK_JOBTYPE_TO_MATCHING_S&F
    FOREIGN KEY (JOBTYPE_ID)
    REFERENCES JOBTYPE (JOBTYPE_ID);

ALTER TABLE MATCHING_S&F
  ADD CONSTRAINT FK_SERVICEAREA_TO_MATCHING_S&F
    FOREIGN KEY (SERVICEAREA_ID)
    REFERENCES SERVICEAREA (SERVICEAREA_ID);

ALTER TABLE MATCHING_S&F
  ADD CONSTRAINT FK_CAR&LICENSE_TO_MATCHING_S&F
    FOREIGN KEY (CAR&LICENCE_ID)
    REFERENCES CAR&LICENSE (CAR&LICENCE_ID);

ALTER TABLE MATCHING_S&F
  ADD CONSTRAINT FK_CERTIFICATION_TO_MATCHING_S&F
    FOREIGN KEY (CERTIFICATION_ID)
    REFERENCES CERTIFICATION (CERTIFICATION_ID);
