
CREATE TABLE CLINICNAME
(
  CLINICNAME VARCHAR(50) NOT NULL COMMENT '병원이름',
  PRIMARY KEY (CLINICNAME)
) COMMENT '병원이름';

CREATE TABLE GENDER
(
  GENDER    VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_ID VARCHAR(50) NOT NULL COMMENT '성별ID',
  PRIMARY KEY (GENDER_ID)
) COMMENT '성별';

CREATE TABLE MEDICALDEPARTMENT
(
  MEDICALDEPARTMENT    VARCHAR(50) NOT NULL COMMENT '진료과',
  MEDICALDEPARTMENT_ID VARCHAR(50) NOT NULL COMMENT '진료과ID',
  CLINICNAME           VARCHAR(50) NOT NULL COMMENT '병원이름',
  PRIMARY KEY (MEDICALDEPARTMENT_ID)
) COMMENT '진료과';

CREATE TABLE MEMBER_D
(
  PHOTO        VARCHAR(500) NOT NULL COMMENT '회원 사진',
  TYPE_ID      VARCHAR(50)  NOT NULL COMMENT '회원유형ID',
  MEMBERID     VARCHAR(50)  NOT NULL COMMENT '회원아이디',
  PASSWORD     VARCHAR(50)  NOT NULL COMMENT '비밀번호',
  NAME         VARCHAR(50)  NOT NULL COMMENT '이름',
  GENDER_ID    VARCHAR(50)  NOT NULL COMMENT '성별ID',
  BIRTHDATE    INTEGER(50)  NOT NULL COMMENT '생년월일',
  PHONENUMBER  INTEGER(50)  NOT NULL COMMENT '전화번호',
  ADDRESS      VARCHAR(500) NOT NULL COMMENT '주소',
  EMAIL        VARCHAR(50)  NOT NULL COMMENT '이메일',
  INTRODUCTION VARCHAR(500) NOT NULL COMMENT '자기소개'
) COMMENT '전문의회원DB';

CREATE TABLE MEMBERID
(
  MEMBERID             VARCHAR(50) NOT NULL COMMENT '회원아이디',
  MEDICALDEPARTMENT_ID VARCHAR(50) NOT NULL COMMENT '진료과ID',
  PRIMARY KEY (MEMBERID)
) COMMENT '회원아이디';

CREATE TABLE TYPE
(
  TYPE    VARCHAR(50) NOT NULL COMMENT '회원유형',
  TYPE_ID VARCHAR(50) NOT NULL COMMENT '회원유형ID',
  PRIMARY KEY (TYPE_ID)
) COMMENT '회원유형';

ALTER TABLE MEMBER_D
  ADD CONSTRAINT FK_TYPE_TO_MEMBER_D
    FOREIGN KEY (TYPE_ID)
    REFERENCES TYPE (TYPE_ID);

ALTER TABLE MEMBER_D
  ADD CONSTRAINT FK_GENDER_TO_MEMBER_D
    FOREIGN KEY (GENDER_ID)
    REFERENCES GENDER (GENDER_ID);

ALTER TABLE MEMBER_D
  ADD CONSTRAINT FK_MEMBERID_TO_MEMBER_D
    FOREIGN KEY (MEMBERID)
    REFERENCES MEMBERID (MEMBERID);

ALTER TABLE MEMBERID
  ADD CONSTRAINT FK_MEDICALDEPARTMENT_TO_MEMBERID
    FOREIGN KEY (MEDICALDEPARTMENT_ID)
    REFERENCES MEDICALDEPARTMENT (MEDICALDEPARTMENT_ID);

ALTER TABLE MEDICALDEPARTMENT
  ADD CONSTRAINT FK_CLINICNAME_TO_MEDICALDEPARTMENT
    FOREIGN KEY (CLINICNAME)
    REFERENCES CLINICNAME (CLINICNAME);
