
CREATE TABLE COMMONS_CODE
(
  COMMON_CODE_ID        varchar(40)   NOT NULL COMMENT '공통 코드_ID',
  NAME                  varchar(1000) NOT NULL COMMENT '명칭',
  ORDER_NUMBER          decimal       NULL     COMMENT '정렬순서',
  ATTRIBUTION_1         varchar(60)   NULL     COMMENT '속성_1',
  ATTRIBUTION_2         varchar(60)   NULL     COMMENT '속성_2',
  DESCRIPTION           varchar(1000) NULL     COMMENT '코드설명',
  SYSTEM_CODE_YN        varchar(40)   NOT NULL DEFAULT N COMMENT '초기 시스템 코드 여부',
  USE_YN                varchar(40)   NOT NULL COMMENT '사용 여부',
  REGISTER_SEQ          varchar(50)   NOT NULL COMMENT '등록자SEQ',
  REGISTRY_DATE         varchar(20)   NOT NULL COMMENT '등록일자',
  MODIFIER_SEQ          varchar(40)   NOT NULL COMMENT '수정자_SEQ',
  MODIFY_DATE           varchar(20)   NOT NULL COMMENT '수정일자',
  PARENT_COMMON_CODE_ID varchar(40)   NULL     COMMENT '상위_공통 코드_ID',
  PRIMARY KEY (COMMON_CODE_ID)
);

ALTER TABLE COMMONS_CODE
  ADD CONSTRAINT FK_COMMONS_CODE_TO_COMMONS_CODE
    FOREIGN KEY (PARENT_COMMON_CODE_ID)
    REFERENCES COMMONS_CODE (COMMON_CODE_ID);

CREATE TABLE GENDER
(
  GENDER    VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_ID VARCHAR(50) NOT NULL COMMENT '성별ID',
  PRIMARY KEY (GENDER_ID)
) COMMENT '성별';

CREATE TABLE LEVEL
(
  LEVEL    VARCHAR(50) NOT NULL COMMENT '치매진행단계',
  LEVEL_ID VARCHAR(50) NOT NULL COMMENT '치매진행단계ID',
  PRIMARY KEY (LEVEL_ID)
) COMMENT '치매진행단계';

CREATE TABLE MEDICALDEPARTMENT
(
  MEDICALDEPARTMENT    VARCHAR(50) NOT NULL COMMENT '진료과',
  MEDICALDEPARTMENT_ID VARCHAR(50) NOT NULL COMMENT '진료과ID',
  PRIMARY KEY (MEDICALDEPARTMENT_ID)
) COMMENT '진료과';

CREATE TABLE MEMBER_D
(
  CLINICNAME           VARCHAR(50) NOT NULL COMMENT '병원이름',
  MEMBERID             VARCHAR(50) NOT NULL COMMENT '회원아이디',
  MEDICALDEPARTMENT_ID VARCHAR(50) NOT NULL COMMENT '진료과ID'
) COMMENT '전문의';

CREATE TABLE MEMBER_F
(
  MEMBERID         VARCHAR(50) NOT NULL COMMENT '회원아이디',
  LEVEL_ID         VARCHAR(50) NOT NULL COMMENT '치매진행단계ID',
  PATIENTGENDER_ID VARCHAR(50) NOT NULL COMMENT '환자성별ID'
) COMMENT '가족';

CREATE TABLE MEMBER_S
(
  LEVEL_ID VARCHAR(50) NOT NULL COMMENT '치매진행단계ID',
  MEMBERID VARCHAR(50) NOT NULL COMMENT '회원아이디'
) COMMENT '본인';

CREATE TABLE MEMBERS
(
  PHOTO        VARCHAR(500) NOT NULL COMMENT '회원 사진',
  TYPE_ID      VARCHAR(50)  NOT NULL COMMENT '회원유형ID',
  MEMBERID     VARCHAR(50)  NOT NULL COMMENT '회원아이디',
  PASSWORD     VARCHAR(50)  NOT NULL COMMENT '비밀번호',
  NAME         VARCHAR(50)  NOT NULL COMMENT '이름',
  GENDER_ID    VARCHAR(50)  NOT NULL COMMENT '성별ID',
  BIRTHDATE    INTEGER(50)  NOT NULL COMMENT '생년월일',
  PHONENUMBER  INTEGER(50)  NOT NULL COMMENT '전화번호',
  ADDRESS      VARCHAR(500) NOT NULL COMMENT '주소',
  EMAIL        VARCHAR(50)  NOT NULL COMMENT '이메일',
  INTRODUCTION VARCHAR(500) NOT NULL COMMENT '자기소개',
  PRIMARY KEY (MEMBERID)
) COMMENT '회원DB';

CREATE TABLE PATIENTGENDER
(
  PATIENTGENDER    VARCHAR(50) NOT NULL COMMENT '환자성별',
  PATIENTGENDER_ID VARCHAR(50) NOT NULL COMMENT '환자성별ID',
  PRIMARY KEY (PATIENTGENDER_ID)
) COMMENT '환자성별';

CREATE TABLE TYPE
(
  TYPE    VARCHAR(50) NOT NULL COMMENT '회원유형',
  TYPE_ID VARCHAR(50) NOT NULL COMMENT '회원유형ID',
  PRIMARY KEY (TYPE_ID)
) COMMENT '회원유형';

ALTER TABLE MEMBERS
  ADD CONSTRAINT FK_TYPE_TO_MEMBERS
    FOREIGN KEY (TYPE_ID)
    REFERENCES TYPE (TYPE_ID);

ALTER TABLE MEMBERS
  ADD CONSTRAINT FK_GENDER_TO_MEMBERS
    FOREIGN KEY (GENDER_ID)
    REFERENCES GENDER (GENDER_ID);

ALTER TABLE MEMBER_S
  ADD CONSTRAINT FK_LEVEL_TO_MEMBER_S
    FOREIGN KEY (LEVEL_ID)
    REFERENCES LEVEL (LEVEL_ID);

ALTER TABLE MEMBER_S
  ADD CONSTRAINT FK_MEMBERS_TO_MEMBER_S
    FOREIGN KEY (MEMBERID)
    REFERENCES MEMBERS (MEMBERID);

ALTER TABLE MEMBER_F
  ADD CONSTRAINT FK_MEMBERS_TO_MEMBER_F
    FOREIGN KEY (MEMBERID)
    REFERENCES MEMBERS (MEMBERID);

ALTER TABLE MEMBER_F
  ADD CONSTRAINT FK_LEVEL_TO_MEMBER_F
    FOREIGN KEY (LEVEL_ID)
    REFERENCES LEVEL (LEVEL_ID);

ALTER TABLE MEMBER_F
  ADD CONSTRAINT FK_PATIENTGENDER_TO_MEMBER_F
    FOREIGN KEY (PATIENTGENDER_ID)
    REFERENCES PATIENTGENDER (PATIENTGENDER_ID);

ALTER TABLE MEMBER_D
  ADD CONSTRAINT FK_MEMBERS_TO_MEMBER_D
    FOREIGN KEY (MEMBERID)
    REFERENCES MEMBERS (MEMBERID);

ALTER TABLE MEMBER_D
  ADD CONSTRAINT FK_MEDICALDEPARTMENT_TO_MEMBER_D
    FOREIGN KEY (MEDICALDEPARTMENT_ID)
    REFERENCES MEDICALDEPARTMENT (MEDICALDEPARTMENT_ID);
